### ISSUE TITLE
The Fiber to cancel the client continues to exist until the server is stopped?

### ISSUE THREAD

**Issue by mebubo** [lrodero/cats-effect-tutorial#1]
Hi, thanks for creating this!

Do I understand correctly that the fiber created (here)[https://github.com/lrodero/cats-effect-tutorial/blob/master/src/main/scala/catsEffectTutorial/EchoServerV3_ClosingClientsOnShutdown.scala#L94-L95] continues to exist until the server is stopped? Could this be a problem for a long-running server?

**Comment by lrodero** [comment]
Hi @mebubo ! And sorry for the late reply, I take a look to the repo when I can but it's not that often :/ .

As I understand it, a fiber on an action is not a 'living thread', but just the representation of the result of running that action asynchronously. So in this case it should be safely garbage collected when the action is done.
