### ISSUE TITLE
Wrong package

### ISSUE THREAD

**Issue by jvr-ks** [lrodero/cats-effect-tutorial#5]
package should be:
package catseffecttutorial
not
package catseffecttutorial.copyfile

otherwise the call:
"runMain catseffecttutorial.CopyFile origin.txt destination.txt"
as documented in:
https://typelevel.org/cats-effect/docs/tutorial
fails!

**Comment by lrodero** [comment]
Thanks for raising the issue! And sorry very much I didn't take a look before. `README.md` has been fixed to use the proper packages naming, also the tutorial is fixed by this [PR](https://github.com/typelevel/cats-effect/pull/3761) in cats-effect repo.
