### ISSUE TITLE
Need help with tutorial exercises

### ISSUE THREAD

**Issue by arthan1011** [lrodero/cats-effect-tutorial#7]
Hello, thank you for making this tutorial. I have issues with this tutorial exercise:
**And to ensure that the release functionality in the Resources is run you can add some log message there (see IO.println).**

I tried modifying this line
https://github.com/lrodero/cats-effect-tutorial/blob/4214b276fe9097960b83d78abadb0633ebf6ac27/src/main/scala/catseffecttutorial/copyfile/CopyFilePolymorphic.scala#L48

from
`Sync[F].blocking(outStream.close()).handleErrorWith(_ => Sync[F].unit)`
to
`Sync[F].blocking(outStream.close()).handleErrorWith(_ => IO.println("Error with output stream") >> Sync[F].unit)`

but the compiler gives me this error:

```
\effects_tutorial\src\main\scala\ef\CopyFile.scala:64:127: type mismatch;
[error]  found   : F[Unit]
[error]  required: cats.effect.IO[?]
[error]       outStream => Sync[F].blocking(outStream.close()).handleErrorWith(_ => IO.println("Error with output stream") >> Sync[F].unit)
[error]                                                                                                                               ^
[error] one error found                                                                                                                                                                          
[error] (Compile / compileIncremental) Compilation failed
```

Is it possible to fix this?

**Comment by ppbustamante** [comment]
Hi @arthan1011. I have the same problem, how did you solve it?

Edit:

I already knew how to do it. I saw it later in the next exercise.
